### ISSUE TITLE
Support multiple actions in single README

### ISSUE THREAD

**Issue by shakefu** [npalm/action-docs#205]
We have a use case where we'd like to support having multiple subdirectory actions output their docs to a single README at the top level. Right now `action-docs` only supports the single `<!-- action-docs--... -->` tags which means running it against multiple actions overwrites the previous generated action.

Right now multiple `--action` arguments generates an error (received array instead of string) and running `action-docs` multiple times with different `--action` arguments obviously overwrites the previous runs.

Is this something that could be supported?

**Comment by npalm** [comment]
Nice idea, feel free to raise a PR. I think the GitHub module is still one action per repostiroy, but happy to support the feature here.

**Comment by shakefu** [comment]
> I think the GitHub module is still one action per repostiroy

Actually they point to their own CodeQL actions as an example of multi-action repositories. https://github.com/github/codeql-action

However the Action Marketplace doesn't support multi-action repositories yet. Still works great though.
