### ISSUE TITLE
Table formatting issue in IntelliJ renderer

### ISSUE THREAD

**Issue by klemmari1** [npalm/action-docs#275]
https://github.com/npalm/action-docs/blob/7546ae5c9114d1d2f6a44f26fb7cd315dc755b9f/src/action-docs.ts#L179

Hello!

Question about the formatting of md tables. Is it intentionally set as one hyphen for the column row or should it be three (`"---"`) as per the [GitHub markdown doc](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables):
> There must be at least three hyphens in each column of the header row.

There is no direct mention of the three hyphens in the spec but it still shows three in the example:
https://github.github.com/gfm/#tables-extension-

Mention of this in another spec:
https://www.markdownguide.org/extended-syntax/#tables

The reason I'm asking is because this breaks the tables in the IntelliJ Idea render view, similar to this "bug report":
https://youtrack.jetbrains.com/issue/IDEA-210076/Markdown-tables-are-not-always-rendered-properly-in-preview

**Comment by npalm** [comment]
Would you like to create a PR with a fix?

**Comment by npalm** [comment]
PR merged, closing
