### ISSUE TITLE
Getting error: Cannot read properties of undefined (reading 'using')

### ISSUE THREAD

**Issue by vipulgupta2048** [npalm/action-docs#340]
Facing this error when using action-docs to build docs for https://github.com/product-os/flowzone with command `action-docs --action ./flowzone.yml --update-readme docs.md`

**Comment by dgokcin** [comment]
just hit this

**Comment by npalm** [comment]
The action-docs cli only read action-docs YAML, the flow zone file seems not to be an action docs YAML file.

**Comment by vipulgupta2048** [comment]
Can you give an example of a `action docs YAML file` what makes it different?

**Comment by npalm** [comment]
See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

**Comment by deemp** [comment]
It was due to a missing field in `inputs`.
