### ISSUE TITLE
Support for the multiple steps descriptions in Readme.md file  

### ISSUE THREAD

**Issue by AyushiyNigam-eaton** [npalm/action-docs#420]
need support for adding Stepsname and step description  to be added in README.md file.
 
Sample code : 
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      -name: printing values
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"

    steps:
      -name: setting environment variable 
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"

**Comment by npalm** [comment]
This cli is to generate docs of a github action, not about creating docs of a workflow. Closing the issue, feel free to re-open
