### ISSUE TITLE
Latest version missing from npm

### ISSUE THREAD

**Issue by xiehan** [npalm/action-docs#466]
Was trying to figure out why the new `<!-- action-docs-usage -->` syntax wasn't working for me no matter what I tried when I realized that that was added in v1.3, but npm only has the package up to v1.2: https://www.npmjs.com/package/action-docs

**Comment by nnellanspdl** [comment]
I also ran into this.  I wanted to use this project, but I guess I will have to look at alternatives for now.

**Comment by deemp** [comment]
@nnellanspdl, I've just updated the package. You can now install the package with the `action-docs` binary from GitHub (see https://github.com/npalm/action-docs/pull/505)

**Comment by npalm** [comment]
This is no finally solved. Version 1.3.0 never made it to npm. The new release is no again on NPM.
