### ISSUE TITLE
-a option shows as deprecated in usage but actually has no effect

### ISSUE THREAD

**Issue by LittleColin** [npalm/action-docs#558]
Deprecated option should still work even if it warns - but in the 2.2 release `-a action.yaml` does not have any effect, it still looks for `action.yml` and fails with:

```
ENOENT: no such file or directory, open 'action.yml'
```
Updating to `-s action.yaml` fixed the problem but the option should not show as deprecated in usage. If truly removed, it should cause an error.

**Comment by npalm** [comment]
Just checked, for me the `-a` works. Only when moving up in the dir chain like `action-docs ../action.yml` getting a failing. Same results wioth `-s`

The intention is that `-a` still works (therefore deprecated), any idea @larmitage-bjss

**Comment by npalm** [comment]
Indeed a bug 🐛
