### ISSUE TITLE
Suggestion: Add documentation that an input is deprecated

### ISSUE THREAD

**Issue by larmitage-bjss** [npalm/action-docs#564]
When an input is marked as deprecated, there is nothing documented in the inputs table to show this unless you explicitly add something to the description (which is duplication of effort and requires updating if it changes)

E.g. in [Action Docs Action](https://github.com/larmitage-bjss/fork-action-docs-action/tree/update-action-docs), `actionFile` is deprecated in favour of `sourceFile`
![Screenshot 2024-03-11 at 14 24 17](https://github.com/npalm/action-docs/assets/156074260/a916a2d1-4a54-4eac-8dbc-200c7f867907)
![Screenshot 2024-03-11 at 14 30 01](https://github.com/npalm/action-docs/assets/156074260/e4f48919-5963-4c47-92c7-fcafe6d0e60b)

## Suggested change

The documentation could add a line to say the input is deprecated and add the message if given e.g.:

| name | description | required | default |
| --- | --- | --- | --- |
| `actionFile` | <p>The action definition file.<br /><i>Deprecated: This input is replaced by sourceFile</i></p> | `false` | `""` |
| `sourceFile` | <p>The action or workflow definition file.</p> | `false` | `action.yml` |

**Comment by larmitage-bjss** [comment]
I'm looking at adding this

**Comment by larmitage-bjss** [comment]
Opened a PR for this: https://github.com/npalm/action-docs/pull/565

**Comment by npalm** [comment]
merged
