### ISSUE TITLE
Homebrew formula for action-docs

### ISSUE THREAD

**Issue by nitrocode** [npalm/action-docs#666]
Please add homebrew support!

```
brew install action-docs
```

**Comment by TheShiveshNetwork** [comment]
Hey @npalm I'd be interested to work on it, can this issue be assigned to me?

**Comment by TheShiveshNetwork** [comment]
Hey @npalm I'd be interested to work on it.

**Comment by npalm** [comment]
Would be great @TheShiveshNetwork! A few weeks ago I tried to build a single binary with pkg, but this was causing some errors related to ES modules.

**Comment by TheShiveshNetwork** [comment]
Hey, @npalm have you created some PR? I'd like to work alongside you so that we can fix whatever issue comes.

**Comment by npalm** [comment]
No, I did only a 15 minute experiment locally. No PR.

**Comment by nitrocode** [comment]
I was able to get it working locally and put in PR https://github.com/Homebrew/homebrew-core/pull/195773.

**Comment by nitrocode** [comment]
@npalm Since `brew install action-docs` installs 2.5.0, may I get a review on PR https://github.com/npalm/action-docs/pull/735 to keep this formula up to date and update installation docs?

**Comment by nitrocode** [comment]
Oh I thought my PR was merged into main. I saw your comment that it was moved to https://github.com/npalm/action-docs/pull/744. I closed the issue too soon and reopened it. Apologies for pinging everyone.
